name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm i -g @tarojs/cli
      - run: npm test
      - run: npm codecov -t ${{ secrets.CODECOV_TOKEN }}
