name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: unit test
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm i -g @tarojs/cli@2.2.6
      - run: npm test
      - run: npm run codecov -t $CODECOV_TOKEN
